gesdinet_jwt_refresh_token:
  refresh_token_class: App\Entity\Auth\RefreshToken
  ttl: 2592000 # 30days
  token_parameter_name: refreshToken
  single_use: true

  # add refresh token in cookies ----------------
  cookie:
    enabled: true
    same_site: lax               # default value
    path: /                      # default value
    domain: null                 # default value
    http_only: true              # default value
    secure: true                 # default value
    remove_token_from_body: true # default value