services:
  halthcare-crm.database:
    image: postgres:18-alpine    
    container_name: halthcare-crm.database
    environment:
      - POSTGRES_DB=halthcare            # only for dev
      - POSTGRES_USER=user               # only for dev
      - POSTGRES_PASSWORD=password       # only for dev
    ports:
      - "5440:5432"                      # open only for dev    
    networks:
      - Healthcare-CRM
    volumes:
      - halthcare-crm.database:/var/lib/postgresql
      
  cloudbeaver:
    container_name: cloudbeaver
    image: dbeaver/cloudbeaver:latest
    restart: unless-stopped
    ports:
      - "9000:8978"
    networks:
      - Healthcare-CRM
    volumes:
      - halthcare-crm.cloudbeaver:/opt/cloudbeaver/workspace
#    
#  app:
#    container_name: app
#    build:
#      context: .
#      dockerfile: Dockerfile
#    environment:
#      - "ASPNETCORE_ENVIRONMENT=Development"
#      - "ConnectionStrings__SQLServer=Server=database,1433;Database=app;User=SA;Password=Dev_password@1;trustServerCertificate=true;"
#    ports:
#      - "8080:8080"
#    depends_on:
#      - database
#    networks:
#      - Healthcare-CRM
#    deploy:
#      restart_policy:
#        condition: on-failure
#        max_attempts: 3
   
networks:
  Healthcare-CRM:
    driver: bridge 
   
volumes:
  halthcare-crm.database:
  halthcare-crm.cloudbeaver: