<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
        <PackageReference Include="MediatR" Version="14.2.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Abstractions\" />
      <Folder Include="Operations\Managers\Queries\" />
    </ItemGroup>

</Project>
